name: tt2

on:
  pull_request:
    branches:
      - master

jobs:
  try-github-script2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.2.0
        with:
          github-token: ${{github.token}}
          script: |
            console.log("helllllllllllo 33333333 444")
  eslint-test:
    name: Run eslint check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.15.3'
      - run: ./temp