name: check github events

on:
  pull_request:
    branches:
      - master

jobs:
  echo-pr-event:
    runs-on: ubuntu-latest

    steps:
    - name: Print PR event
      if: github.event.pull_request.merged == true
      run: echo $github.event