name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'

      - run: npm install

      # you'll need to add an `id` in order to access output variables
      - uses: codfish/semantic-release-action@master
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.PAT2 }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: echo $RELEASE_VERSION
      - run: echo $RELEASE_VERSION
      - run: echo ${{ steps.semantic.outputs.release-version }}

      - run: echo "$OUTPUTS"
        env:
          OUTPUTS: ${{ toJson(steps.semantic.outputs) }}

          # Defaults to the user or organization that owns the workflow file
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT2 }}

      - name: docker push version
        if: steps.semantic.outputs.new-release-published == 'true'
        run: |
          docker login https://docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
          docker build -t docker.pkg.github.com/lijujose/tradeing_test/tradeing_test:$RELEASE_VERSION .
          docker push docker.pkg.github.com/lijujose/tradeing_test/tradeing_test:$RELEASE_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.PAT2 }}
