name: try github scripts

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/*'
      - 'integration-test/*'
      - 'zkp/_tests_/*'

jobs:
  try-github-script1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.2.0
        with:
          github-token: ${{github.token}}
          script: |
            const owner = context.payload.sender.login;
            const repo = context.payload.repository.name;

            const {data: pullRequests} = await github.pulls.list({
              owner,
              repo,
              base: "master",
              state: "open"
            });

            for (pr of pullRequests) {

              let pullReq = {};
              while (pullReq.mergeable === undefined || pullReq.mergeable === null) {
                pullReq = (
                  await github.pulls.get({
                    owner,
                    repo,
                    pull_number: pr.number
                  })
                ).data;
              }
              if(pullReq.mergeable === false) continue;

              console.log("in here");
              const {data: commitData} = await github.repos.getCommit({
                owner,
                repo,
                ref: pullReq.head.sha
              });

              const {data: check} = await github.checks.create({
                owner,
                repo,
                name: "try-github-script2",
                head_sha: commitData.sha
              });

              await github.checks.update({
                owner,
                repo,
                check_run_id: check.id,
                status: "in_progress"
              });

              await github.checks.update({
                owner,
                repo,
                check_run_id: check.id,
                status: "completed",
                conclusion: "success"
              });
            }
