name: try github scripts

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/*'
      - 'integration-test/*'
      - 'zkp/_tests_/*'

jobs:
  try-github-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.2.0
        with:
          github-token: ${{github.token}}
          script: |
            const owner = context.payload.sender.login;
            const repo = context.payload.repository.name;

            const {data: pullRequests} = await github.pulls.list({
              owner,
              repo,
              base: "master",
              state: "open"
            });

            for (pr of pullRequests) {

              let pullReq = {};
              while (pullReq.mergeable === undefined || pullReq.mergeable === null) {
                pullReq = (
                  await github.pulls.get({
                    owner,
                    repo,
                    pull_number: pr.number
                  })
                ).data;
              }
              if(pullReq.mergeable === false) continue;

              /*
              const {data: content} = await github.repos.getContents({
                owner,
                repo,
                ref: pr.head.ref,
                path: "github-action-use1.txt",
              });
              
              const data = await github.repos.createOrUpdateFile({
                owner,
                repo,
                message: "trigger github action",
                branch: pr.head.ref,
                content: "",
                sha: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
                path: "github-action-use1.txt",
                commiter: context.payload.pusher,
                author: context.payload.pusher,
              });

              console.log("in here");
              const {data: commitData} = await github.repos.getCommit({
                owner,
                repo,
                ref: pullReq.head.sha
              });

              const {data: createdCommit} = await github.git.createCommit({
                owner,
                repo,
                message: "tigger github actions",
                tree: commitData.commit.tree.sha,
                parents: [commitData.sha],
                commiter: context.payload.pusher,
                author: context.payload.pusher,
              });

              await github.git.updateRef({
                owner,
                repo,
                ref: `heads/${pr.head.ref}`,
                sha: createdCommit.sha
              });
              */
            }
      - uses: actions/checkout@master
      - name: create an empty commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit --allow-empty -m"trigger GitHub actions" 
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}    
          branch: "temp1"   
