name: try github scripts

on:
  push:
    branches:
      - master

jobs:
  try-github-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.2.0
        with:
          github-token: ${{github.token}}
          script: |
            const owner = context.payload.sender.login;
            const repo = context.payload.repository.name;
            const commitHash = context.payload.after;

            const commitRec = await github.repo.getCommit({
              owner,
              repo,
              commit_sha: commitHash
            });

            console.log(commitRec);

            const {data: pullRequests} = await github.pulls.list({
              owner,
              repo,
              base: "master",
              state: "open"
            });

            github.registerEndpoints({
              pr: {
                commits: {
                  method: "GET",
                  url: "/repos/:owner/:repo/commits/:branch",
                  headers: {
                    accept: "application/vnd.github.foo-bar-preview+json"
                  },
                  params: {
                    owner: {
                      required: true,
                      type: "string"
                    },
                    repo: {
                      required: true,
                      type: "string"
                    },
                    branch: {
                      required: true,
                      type: "string"
                    }
                  }
                }
              }
            });

            for (pr of pullRequests) {
              const {data: commit} = await github.pr.commits({
                owner,
                repo,
                branch: pr.head.ref
              });
              console.log(commit.sha, pr.number);
            }
            
