name: try github scripts

on:
  push:
    branches:
      - master

jobs:
  try-github-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.2.0
        with:
          github-token: ${{github.token}}
          script: |
            const owner = context.payload.sender.login;
            const repo = context.payload.repository.name;
            const pushedCommitHash = context.payload.after;
            let runGithubActions = false;

            const {data: { files }} = await github.repos.getCommit({
              owner,
              repo,
              ref: pushedCommitHash
            });

            for (file of files) {
              if (file.filename.includes(".github/workflows/")) {
                runGithubActions = true; 
                break;
              }
              if (file.filename.includes("integration-test/")) {
                runGithubActions = true; 
                break;
              }
              if (file.filename.includes("zkp/_tests_/")) {
                runGithubActions = true; 
                break;
              }
            }

            if (!runGithubActions) return;

            const {data: pullRequests} = await github.pulls.list({
              owner,
              repo,
              base: "master",
              state: "open"
            });

            for (pr of pullRequests) {

              let pullReq = {};
              while (pullReq.mergeable === undefined || pullReq.mergeable === null) {
                pullReq = (
                  await github.pulls.get({
                    owner,
                    repo,
                    pull_number: pr.number
                  })
                ).data;
              }
              if(pullReq.mergeable === false) continue;

              const {data: commit} = await github.git.getRef({
                owner,
                repo,
                branch: pr.head.ref
              });
              console.log(commit);
              const {data: createdCommit} = await github.git.createCommit({
                owner,
                repo,
                message: "tigger github actions",
                tree: commit.commit.tree.sha,
                parents: [commit.sha],
                author: context.payload.pusher
              });
  
              await github.git.updateRef({
                owner,
                repo,
                ref: `heads/${pr.head.ref}`,
                sha: createdCommit.sha
              });
            }
            
