name: try github scripts

on:
  push:
    branches:
      - master

jobs:
  try-github-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.2.0
        with:
          github-token: ${{github.token}}
          script: |
            console.log(context)
            console.log("*******", github.token, "************")
            console.log(Object.keys(github.pullRequests))
            const owner = context.payload.sender.login;
            const repo = context.payload.repository.name;
            const status = await github.pulls.get({
              owner,
              repo,
              pull_number: 6,
              base: "temp2"
            });
            console.log(status);
