name: try github scripts

on:
  push:
    branches:
      - master

jobs:
  try-github-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.2.0
        with:
          github-token: ${{github.token}}
          script: |
            const owner = context.payload.sender.login;
            const repo = context.payload.repository.name;
            const {data: pullRequests} = await github.pulls.list({
              owner,
              repo,
              base: "master",
              state: "open"
            });
            console.log(pullRequests);

            github.registerEndpoints({
              pr: {
                commits: {
                  method: "GET",
                  url: "/repos/:owner/:repo/commits",
                  headers: {
                    accept: "application/vnd.github.foo-bar-preview+json"
                  },
                  params: {
                    owner: {
                      required: true,
                      type: "string"
                    },
                    repo: {
                      required: true,
                      type: "string"
                    },
                    sha: {
                      required: true,
                      type: "string"
                    }
                  }
                }
              }
            });

            const {data: commits} = await github.pr.commits({
              owner,
              repo,
              sha: pullRequests[0].head.ref
            });
            console.log(commits, pullRequests[0].number);
