name: try github scripts

on:
  push:
    branches:
      - master

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.2.0
        with:
          github-token: ${{github.token}}
          script: |
            const diff_url = context.payload.pull_request.diff_url
            console.log(github.token)