name: tt2

on:
  check_run:
    types: [rerequested, requested_action]

jobs:
  try-github-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.2.0
        with:
          github-token: ${{github.token}}
          script: |
            console.log("helllllllllllo check_run")
